#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="aplicacao_2025")]
	public partial class DCAplicacaoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertacao(acao instance);
    partial void Updateacao(acao instance);
    partial void Deleteacao(acao instance);
    partial void Insertstatus(status instance);
    partial void Updatestatus(status instance);
    partial void Deletestatus(status instance);
    partial void Insertconfiguracao(configuracao instance);
    partial void Updateconfiguracao(configuracao instance);
    partial void Deleteconfiguracao(configuracao instance);
    partial void InsertDicionario(Dicionario instance);
    partial void UpdateDicionario(Dicionario instance);
    partial void DeleteDicionario(Dicionario instance);
    partial void Insertdocumento(documento instance);
    partial void Updatedocumento(documento instance);
    partial void Deletedocumento(documento instance);
    partial void Insertestrutura(estrutura instance);
    partial void Updateestrutura(estrutura instance);
    partial void Deleteestrutura(estrutura instance);
    partial void Insertevento(evento instance);
    partial void Updateevento(evento instance);
    partial void Deleteevento(evento instance);
    partial void Insertgrupo(grupo instance);
    partial void Updategrupo(grupo instance);
    partial void Deletegrupo(grupo instance);
    partial void InsertGrupoProcesso(GrupoProcesso instance);
    partial void UpdateGrupoProcesso(GrupoProcesso instance);
    partial void DeleteGrupoProcesso(GrupoProcesso instance);
    partial void InsertGrupoUsuario(GrupoUsuario instance);
    partial void UpdateGrupoUsuario(GrupoUsuario instance);
    partial void DeleteGrupoUsuario(GrupoUsuario instance);
    partial void Inserthistorico(historico instance);
    partial void Updatehistorico(historico instance);
    partial void Deletehistorico(historico instance);
    partial void Insertnotificacao(notificacao instance);
    partial void Updatenotificacao(notificacao instance);
    partial void Deletenotificacao(notificacao instance);
    partial void InsertOcorrencia(Ocorrencia instance);
    partial void UpdateOcorrencia(Ocorrencia instance);
    partial void DeleteOcorrencia(Ocorrencia instance);
    partial void Insertpagina(pagina instance);
    partial void Updatepagina(pagina instance);
    partial void Deletepagina(pagina instance);
    partial void Insertpasta(pasta instance);
    partial void Updatepasta(pasta instance);
    partial void Deletepasta(pasta instance);
    partial void Insertprocesso(processo instance);
    partial void Updateprocesso(processo instance);
    partial void Deleteprocesso(processo instance);
    partial void InsertProcessoUsuario(ProcessoUsuario instance);
    partial void UpdateProcessoUsuario(ProcessoUsuario instance);
    partial void DeleteProcessoUsuario(ProcessoUsuario instance);
    partial void Insertregistro(registro instance);
    partial void Updateregistro(registro instance);
    partial void Deleteregistro(registro instance);
    #endregion
		
		public DCAplicacaoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCAplicacaoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCAplicacaoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCAplicacaoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<acao> acaos
		{
			get
			{
				return this.GetTable<acao>();
			}
		}
		
		public System.Data.Linq.Table<status> status
		{
			get
			{
				return this.GetTable<status>();
			}
		}
		
		public System.Data.Linq.Table<configuracao> configuracaos
		{
			get
			{
				return this.GetTable<configuracao>();
			}
		}
		
		public System.Data.Linq.Table<Dicionario> Dicionarios
		{
			get
			{
				return this.GetTable<Dicionario>();
			}
		}
		
		public System.Data.Linq.Table<documento> documentos
		{
			get
			{
				return this.GetTable<documento>();
			}
		}
		
		public System.Data.Linq.Table<estrutura> estruturas
		{
			get
			{
				return this.GetTable<estrutura>();
			}
		}
		
		public System.Data.Linq.Table<evento> eventos
		{
			get
			{
				return this.GetTable<evento>();
			}
		}
		
		public System.Data.Linq.Table<grupo> grupos
		{
			get
			{
				return this.GetTable<grupo>();
			}
		}
		
		public System.Data.Linq.Table<GrupoProcesso> GrupoProcessos
		{
			get
			{
				return this.GetTable<GrupoProcesso>();
			}
		}
		
		public System.Data.Linq.Table<GrupoUsuario> GrupoUsuarios
		{
			get
			{
				return this.GetTable<GrupoUsuario>();
			}
		}
		
		public System.Data.Linq.Table<historico> historicos
		{
			get
			{
				return this.GetTable<historico>();
			}
		}
		
		public System.Data.Linq.Table<notificacao> notificacaos
		{
			get
			{
				return this.GetTable<notificacao>();
			}
		}
		
		public System.Data.Linq.Table<Ocorrencia> Ocorrencias
		{
			get
			{
				return this.GetTable<Ocorrencia>();
			}
		}
		
		public System.Data.Linq.Table<pagina> paginas
		{
			get
			{
				return this.GetTable<pagina>();
			}
		}
		
		public System.Data.Linq.Table<pasta> pastas
		{
			get
			{
				return this.GetTable<pasta>();
			}
		}
		
		public System.Data.Linq.Table<processo> processos
		{
			get
			{
				return this.GetTable<processo>();
			}
		}
		
		public System.Data.Linq.Table<ProcessoUsuario> ProcessoUsuarios
		{
			get
			{
				return this.GetTable<ProcessoUsuario>();
			}
		}
		
		public System.Data.Linq.Table<registro> registros
		{
			get
			{
				return this.GetTable<registro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.acao")]
	public partial class acao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Guid _usuarioid;
		
		private System.DateTime _data;
		
		private string _descricao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusuarioidChanging(System.Guid value);
    partial void OnusuarioidChanged();
    partial void OndataChanging(System.DateTime value);
    partial void OndataChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    #endregion
		
		public acao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid usuarioid
		{
			get
			{
				return this._usuarioid;
			}
			set
			{
				if ((this._usuarioid != value))
				{
					this.OnusuarioidChanging(value);
					this.SendPropertyChanging();
					this._usuarioid = value;
					this.SendPropertyChanged("usuarioid");
					this.OnusuarioidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="DateTime NOT NULL")]
		public System.DateTime data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.status")]
	public partial class status : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _descricao;
		
		private EntitySet<documento> _documentos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    #endregion
		
		public status()
		{
			this._documentos = new EntitySet<documento>(new Action<documento>(this.attach_documentos), new Action<documento>(this.detach_documentos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="status_documento", Storage="_documentos", ThisKey="id", OtherKey="statusid")]
		public EntitySet<documento> documentos
		{
			get
			{
				return this._documentos;
			}
			set
			{
				this._documentos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_documentos(documento entity)
		{
			this.SendPropertyChanging();
			entity.status = this;
		}
		
		private void detach_documentos(documento entity)
		{
			this.SendPropertyChanging();
			entity.status = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.configuracao")]
	public partial class configuracao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _valor;
		
		private string _campo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnvalorChanging(string value);
    partial void OnvalorChanged();
    partial void OncampoChanging(string value);
    partial void OncampoChanged();
    #endregion
		
		public configuracao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="VarChar(480) NOT NULL", CanBeNull=false)]
		public string valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo", DbType="VarChar(480) NOT NULL", CanBeNull=false)]
		public string campo
		{
			get
			{
				return this._campo;
			}
			set
			{
				if ((this._campo != value))
				{
					this.OncampoChanging(value);
					this.SendPropertyChanging();
					this._campo = value;
					this.SendPropertyChanged("campo");
					this.OncampoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dicionario")]
	public partial class Dicionario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _palavra;
		
		private EntitySet<Ocorrencia> _Ocorrencias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpalavraChanging(string value);
    partial void OnpalavraChanged();
    #endregion
		
		public Dicionario()
		{
			this._Ocorrencias = new EntitySet<Ocorrencia>(new Action<Ocorrencia>(this.attach_Ocorrencias), new Action<Ocorrencia>(this.detach_Ocorrencias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string palavra
		{
			get
			{
				return this._palavra;
			}
			set
			{
				if ((this._palavra != value))
				{
					this.OnpalavraChanging(value);
					this.SendPropertyChanging();
					this._palavra = value;
					this.SendPropertyChanged("palavra");
					this.OnpalavraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dicionario_Ocorrencia", Storage="_Ocorrencias", ThisKey="id", OtherKey="palavraid")]
		public EntitySet<Ocorrencia> Ocorrencias
		{
			get
			{
				return this._Ocorrencias;
			}
			set
			{
				this._Ocorrencias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ocorrencias(Ocorrencia entity)
		{
			this.SendPropertyChanging();
			entity.Dicionario = this;
		}
		
		private void detach_Ocorrencias(Ocorrencia entity)
		{
			this.SendPropertyChanging();
			entity.Dicionario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.documento")]
	public partial class documento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _arquivo;
		
		private System.DateTime _data;
		
		private int _statusid;
		
		private System.Guid _usuarioid;
		
		private int _pagina;
		
		private string _hash;
		
		private bool _ativo;
		
		private string _conteudo;
		
		private int _pastaid;
		
		private string _chave;
		
		private int _processoid;
		
		private int _ordProc;
		
		private bool _indexado;
		
		private string _observacoes;
		
		private EntitySet<historico> _historicos;
		
		private EntitySet<pagina> _paginas;
		
		private EntityRef<status> _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnarquivoChanging(string value);
    partial void OnarquivoChanged();
    partial void OndataChanging(System.DateTime value);
    partial void OndataChanged();
    partial void OnstatusidChanging(int value);
    partial void OnstatusidChanged();
    partial void OnusuarioidChanging(System.Guid value);
    partial void OnusuarioidChanged();
    partial void OnpaginaChanging(int value);
    partial void OnpaginaChanged();
    partial void OnhashChanging(string value);
    partial void OnhashChanged();
    partial void OnativoChanging(bool value);
    partial void OnativoChanged();
    partial void OnconteudoChanging(string value);
    partial void OnconteudoChanged();
    partial void OnpastaidChanging(int value);
    partial void OnpastaidChanged();
    partial void OnchaveChanging(string value);
    partial void OnchaveChanged();
    partial void OnprocessoidChanging(int value);
    partial void OnprocessoidChanged();
    partial void OnordProcChanging(int value);
    partial void OnordProcChanged();
    partial void OnindexadoChanging(bool value);
    partial void OnindexadoChanged();
    partial void OnobservacoesChanging(string value);
    partial void OnobservacoesChanged();
    #endregion
		
		public documento()
		{
			this._historicos = new EntitySet<historico>(new Action<historico>(this.attach_historicos), new Action<historico>(this.detach_historicos));
			this._paginas = new EntitySet<pagina>(new Action<pagina>(this.attach_paginas), new Action<pagina>(this.detach_paginas));
			this._status = default(EntityRef<status>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arquivo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string arquivo
		{
			get
			{
				return this._arquivo;
			}
			set
			{
				if ((this._arquivo != value))
				{
					this.OnarquivoChanging(value);
					this.SendPropertyChanging();
					this._arquivo = value;
					this.SendPropertyChanged("arquivo");
					this.OnarquivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="DateTime NOT NULL")]
		public System.DateTime data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusid", DbType="Int NOT NULL")]
		public int statusid
		{
			get
			{
				return this._statusid;
			}
			set
			{
				if ((this._statusid != value))
				{
					if (this._status.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstatusidChanging(value);
					this.SendPropertyChanging();
					this._statusid = value;
					this.SendPropertyChanged("statusid");
					this.OnstatusidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid usuarioid
		{
			get
			{
				return this._usuarioid;
			}
			set
			{
				if ((this._usuarioid != value))
				{
					this.OnusuarioidChanging(value);
					this.SendPropertyChanging();
					this._usuarioid = value;
					this.SendPropertyChanged("usuarioid");
					this.OnusuarioidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pagina", DbType="Int NOT NULL")]
		public int pagina
		{
			get
			{
				return this._pagina;
			}
			set
			{
				if ((this._pagina != value))
				{
					this.OnpaginaChanging(value);
					this.SendPropertyChanging();
					this._pagina = value;
					this.SendPropertyChanged("pagina");
					this.OnpaginaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hash", DbType="VarChar(255)")]
		public string hash
		{
			get
			{
				return this._hash;
			}
			set
			{
				if ((this._hash != value))
				{
					this.OnhashChanging(value);
					this.SendPropertyChanging();
					this._hash = value;
					this.SendPropertyChanged("hash");
					this.OnhashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ativo", DbType="Bit NOT NULL")]
		public bool ativo
		{
			get
			{
				return this._ativo;
			}
			set
			{
				if ((this._ativo != value))
				{
					this.OnativoChanging(value);
					this.SendPropertyChanging();
					this._ativo = value;
					this.SendPropertyChanged("ativo");
					this.OnativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conteudo", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string conteudo
		{
			get
			{
				return this._conteudo;
			}
			set
			{
				if ((this._conteudo != value))
				{
					this.OnconteudoChanging(value);
					this.SendPropertyChanging();
					this._conteudo = value;
					this.SendPropertyChanged("conteudo");
					this.OnconteudoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pastaid", DbType="Int NOT NULL")]
		public int pastaid
		{
			get
			{
				return this._pastaid;
			}
			set
			{
				if ((this._pastaid != value))
				{
					this.OnpastaidChanging(value);
					this.SendPropertyChanging();
					this._pastaid = value;
					this.SendPropertyChanged("pastaid");
					this.OnpastaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chave", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string chave
		{
			get
			{
				return this._chave;
			}
			set
			{
				if ((this._chave != value))
				{
					this.OnchaveChanging(value);
					this.SendPropertyChanging();
					this._chave = value;
					this.SendPropertyChanged("chave");
					this.OnchaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_processoid", DbType="Int NOT NULL")]
		public int processoid
		{
			get
			{
				return this._processoid;
			}
			set
			{
				if ((this._processoid != value))
				{
					this.OnprocessoidChanging(value);
					this.SendPropertyChanging();
					this._processoid = value;
					this.SendPropertyChanged("processoid");
					this.OnprocessoidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ordProc", DbType="Int NOT NULL")]
		public int ordProc
		{
			get
			{
				return this._ordProc;
			}
			set
			{
				if ((this._ordProc != value))
				{
					this.OnordProcChanging(value);
					this.SendPropertyChanging();
					this._ordProc = value;
					this.SendPropertyChanged("ordProc");
					this.OnordProcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indexado", DbType="Bit NOT NULL")]
		public bool indexado
		{
			get
			{
				return this._indexado;
			}
			set
			{
				if ((this._indexado != value))
				{
					this.OnindexadoChanging(value);
					this.SendPropertyChanging();
					this._indexado = value;
					this.SendPropertyChanged("indexado");
					this.OnindexadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoes", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string observacoes
		{
			get
			{
				return this._observacoes;
			}
			set
			{
				if ((this._observacoes != value))
				{
					this.OnobservacoesChanging(value);
					this.SendPropertyChanging();
					this._observacoes = value;
					this.SendPropertyChanged("observacoes");
					this.OnobservacoesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="documento_historico", Storage="_historicos", ThisKey="id", OtherKey="documentoid")]
		public EntitySet<historico> historicos
		{
			get
			{
				return this._historicos;
			}
			set
			{
				this._historicos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="documento_pagina", Storage="_paginas", ThisKey="id", OtherKey="documentoid")]
		public EntitySet<pagina> paginas
		{
			get
			{
				return this._paginas;
			}
			set
			{
				this._paginas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="status_documento", Storage="_status", ThisKey="statusid", OtherKey="id", IsForeignKey=true)]
		public status status
		{
			get
			{
				return this._status.Entity;
			}
			set
			{
				status previousValue = this._status.Entity;
				if (((previousValue != value) 
							|| (this._status.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._status.Entity = null;
						previousValue.documentos.Remove(this);
					}
					this._status.Entity = value;
					if ((value != null))
					{
						value.documentos.Add(this);
						this._statusid = value.id;
					}
					else
					{
						this._statusid = default(int);
					}
					this.SendPropertyChanged("status");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_historicos(historico entity)
		{
			this.SendPropertyChanging();
			entity.documento = this;
		}
		
		private void detach_historicos(historico entity)
		{
			this.SendPropertyChanging();
			entity.documento = null;
		}
		
		private void attach_paginas(pagina entity)
		{
			this.SendPropertyChanging();
			entity.documento = this;
		}
		
		private void detach_paginas(pagina entity)
		{
			this.SendPropertyChanging();
			entity.documento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.estrutura")]
	public partial class estrutura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _estruturasuperiorid;
		
		private string _nome;
		
		private EntitySet<processo> _processos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnestruturasuperioridChanging(int value);
    partial void OnestruturasuperioridChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    #endregion
		
		public estrutura()
		{
			this._processos = new EntitySet<processo>(new Action<processo>(this.attach_processos), new Action<processo>(this.detach_processos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estruturasuperiorid", DbType="Int NOT NULL")]
		public int estruturasuperiorid
		{
			get
			{
				return this._estruturasuperiorid;
			}
			set
			{
				if ((this._estruturasuperiorid != value))
				{
					this.OnestruturasuperioridChanging(value);
					this.SendPropertyChanging();
					this._estruturasuperiorid = value;
					this.SendPropertyChanged("estruturasuperiorid");
					this.OnestruturasuperioridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="estrutura_processo", Storage="_processos", ThisKey="id", OtherKey="estruturaid")]
		public EntitySet<processo> processos
		{
			get
			{
				return this._processos;
			}
			set
			{
				this._processos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_processos(processo entity)
		{
			this.SendPropertyChanging();
			entity.estrutura = this;
		}
		
		private void detach_processos(processo entity)
		{
			this.SendPropertyChanging();
			entity.estrutura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.evento")]
	public partial class evento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _processoid;
		
		private System.DateTime _data;
		
		private string _descricao;
		
		private System.Guid _usuarioid;
		
		private int _documentoid;
		
		private int _pastaid;
		
		private EntityRef<processo> _processo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnprocessoidChanging(int value);
    partial void OnprocessoidChanged();
    partial void OndataChanging(System.DateTime value);
    partial void OndataChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    partial void OnusuarioidChanging(System.Guid value);
    partial void OnusuarioidChanged();
    partial void OndocumentoidChanging(int value);
    partial void OndocumentoidChanged();
    partial void OnpastaidChanging(int value);
    partial void OnpastaidChanged();
    #endregion
		
		public evento()
		{
			this._processo = default(EntityRef<processo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_processoid", DbType="Int NOT NULL")]
		public int processoid
		{
			get
			{
				return this._processoid;
			}
			set
			{
				if ((this._processoid != value))
				{
					if (this._processo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnprocessoidChanging(value);
					this.SendPropertyChanging();
					this._processoid = value;
					this.SendPropertyChanged("processoid");
					this.OnprocessoidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="DateTime NOT NULL")]
		public System.DateTime data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid usuarioid
		{
			get
			{
				return this._usuarioid;
			}
			set
			{
				if ((this._usuarioid != value))
				{
					this.OnusuarioidChanging(value);
					this.SendPropertyChanging();
					this._usuarioid = value;
					this.SendPropertyChanged("usuarioid");
					this.OnusuarioidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_documentoid", DbType="Int NOT NULL")]
		public int documentoid
		{
			get
			{
				return this._documentoid;
			}
			set
			{
				if ((this._documentoid != value))
				{
					this.OndocumentoidChanging(value);
					this.SendPropertyChanging();
					this._documentoid = value;
					this.SendPropertyChanged("documentoid");
					this.OndocumentoidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pastaid", DbType="Int NOT NULL")]
		public int pastaid
		{
			get
			{
				return this._pastaid;
			}
			set
			{
				if ((this._pastaid != value))
				{
					this.OnpastaidChanging(value);
					this.SendPropertyChanging();
					this._pastaid = value;
					this.SendPropertyChanged("pastaid");
					this.OnpastaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="processo_evento", Storage="_processo", ThisKey="processoid", OtherKey="id", IsForeignKey=true)]
		public processo processo
		{
			get
			{
				return this._processo.Entity;
			}
			set
			{
				processo previousValue = this._processo.Entity;
				if (((previousValue != value) 
							|| (this._processo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._processo.Entity = null;
						previousValue.eventos.Remove(this);
					}
					this._processo.Entity = value;
					if ((value != null))
					{
						value.eventos.Add(this);
						this._processoid = value.id;
					}
					else
					{
						this._processoid = default(int);
					}
					this.SendPropertyChanged("processo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.grupo")]
	public partial class grupo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nome;
		
		private int _grupopaiid;
		
		private string _observacoes;
		
		private EntitySet<GrupoProcesso> _GrupoProcessos;
		
		private EntitySet<GrupoUsuario> _GrupoUsuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OngrupopaiidChanging(int value);
    partial void OngrupopaiidChanged();
    partial void OnobservacoesChanging(string value);
    partial void OnobservacoesChanged();
    #endregion
		
		public grupo()
		{
			this._GrupoProcessos = new EntitySet<GrupoProcesso>(new Action<GrupoProcesso>(this.attach_GrupoProcessos), new Action<GrupoProcesso>(this.detach_GrupoProcessos));
			this._GrupoUsuarios = new EntitySet<GrupoUsuario>(new Action<GrupoUsuario>(this.attach_GrupoUsuarios), new Action<GrupoUsuario>(this.detach_GrupoUsuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupopaiid", DbType="Int NOT NULL")]
		public int grupopaiid
		{
			get
			{
				return this._grupopaiid;
			}
			set
			{
				if ((this._grupopaiid != value))
				{
					this.OngrupopaiidChanging(value);
					this.SendPropertyChanging();
					this._grupopaiid = value;
					this.SendPropertyChanged("grupopaiid");
					this.OngrupopaiidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoes", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string observacoes
		{
			get
			{
				return this._observacoes;
			}
			set
			{
				if ((this._observacoes != value))
				{
					this.OnobservacoesChanging(value);
					this.SendPropertyChanging();
					this._observacoes = value;
					this.SendPropertyChanged("observacoes");
					this.OnobservacoesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grupo_GrupoProcesso", Storage="_GrupoProcessos", ThisKey="id", OtherKey="grupoID")]
		public EntitySet<GrupoProcesso> GrupoProcessos
		{
			get
			{
				return this._GrupoProcessos;
			}
			set
			{
				this._GrupoProcessos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grupo_GrupoUsuario", Storage="_GrupoUsuarios", ThisKey="id", OtherKey="grupoID")]
		public EntitySet<GrupoUsuario> GrupoUsuarios
		{
			get
			{
				return this._GrupoUsuarios;
			}
			set
			{
				this._GrupoUsuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GrupoProcessos(GrupoProcesso entity)
		{
			this.SendPropertyChanging();
			entity.grupo = this;
		}
		
		private void detach_GrupoProcessos(GrupoProcesso entity)
		{
			this.SendPropertyChanging();
			entity.grupo = null;
		}
		
		private void attach_GrupoUsuarios(GrupoUsuario entity)
		{
			this.SendPropertyChanging();
			entity.grupo = this;
		}
		
		private void detach_GrupoUsuarios(GrupoUsuario entity)
		{
			this.SendPropertyChanging();
			entity.grupo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GrupoProcesso")]
	public partial class GrupoProcesso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _grupoID;
		
		private int _processoid;
		
		private EntityRef<grupo> _grupo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OngrupoIDChanging(int value);
    partial void OngrupoIDChanged();
    partial void OnprocessoidChanging(int value);
    partial void OnprocessoidChanged();
    #endregion
		
		public GrupoProcesso()
		{
			this._grupo = default(EntityRef<grupo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupoID", DbType="Int NOT NULL")]
		public int grupoID
		{
			get
			{
				return this._grupoID;
			}
			set
			{
				if ((this._grupoID != value))
				{
					if (this._grupo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OngrupoIDChanging(value);
					this.SendPropertyChanging();
					this._grupoID = value;
					this.SendPropertyChanged("grupoID");
					this.OngrupoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_processoid", DbType="Int NOT NULL")]
		public int processoid
		{
			get
			{
				return this._processoid;
			}
			set
			{
				if ((this._processoid != value))
				{
					this.OnprocessoidChanging(value);
					this.SendPropertyChanging();
					this._processoid = value;
					this.SendPropertyChanged("processoid");
					this.OnprocessoidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grupo_GrupoProcesso", Storage="_grupo", ThisKey="grupoID", OtherKey="id", IsForeignKey=true)]
		public grupo grupo
		{
			get
			{
				return this._grupo.Entity;
			}
			set
			{
				grupo previousValue = this._grupo.Entity;
				if (((previousValue != value) 
							|| (this._grupo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._grupo.Entity = null;
						previousValue.GrupoProcessos.Remove(this);
					}
					this._grupo.Entity = value;
					if ((value != null))
					{
						value.GrupoProcessos.Add(this);
						this._grupoID = value.id;
					}
					else
					{
						this._grupoID = default(int);
					}
					this.SendPropertyChanged("grupo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GrupoUsuario")]
	public partial class GrupoUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Guid _usuarioID;
		
		private int _grupoID;
		
		private string _observacoes;
		
		private EntityRef<grupo> _grupo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusuarioIDChanging(System.Guid value);
    partial void OnusuarioIDChanged();
    partial void OngrupoIDChanging(int value);
    partial void OngrupoIDChanged();
    partial void OnobservacoesChanging(string value);
    partial void OnobservacoesChanged();
    #endregion
		
		public GrupoUsuario()
		{
			this._grupo = default(EntityRef<grupo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid usuarioID
		{
			get
			{
				return this._usuarioID;
			}
			set
			{
				if ((this._usuarioID != value))
				{
					this.OnusuarioIDChanging(value);
					this.SendPropertyChanging();
					this._usuarioID = value;
					this.SendPropertyChanged("usuarioID");
					this.OnusuarioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupoID", DbType="Int NOT NULL")]
		public int grupoID
		{
			get
			{
				return this._grupoID;
			}
			set
			{
				if ((this._grupoID != value))
				{
					if (this._grupo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OngrupoIDChanging(value);
					this.SendPropertyChanging();
					this._grupoID = value;
					this.SendPropertyChanged("grupoID");
					this.OngrupoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoes", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string observacoes
		{
			get
			{
				return this._observacoes;
			}
			set
			{
				if ((this._observacoes != value))
				{
					this.OnobservacoesChanging(value);
					this.SendPropertyChanging();
					this._observacoes = value;
					this.SendPropertyChanged("observacoes");
					this.OnobservacoesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grupo_GrupoUsuario", Storage="_grupo", ThisKey="grupoID", OtherKey="id", IsForeignKey=true)]
		public grupo grupo
		{
			get
			{
				return this._grupo.Entity;
			}
			set
			{
				grupo previousValue = this._grupo.Entity;
				if (((previousValue != value) 
							|| (this._grupo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._grupo.Entity = null;
						previousValue.GrupoUsuarios.Remove(this);
					}
					this._grupo.Entity = value;
					if ((value != null))
					{
						value.GrupoUsuarios.Add(this);
						this._grupoID = value.id;
					}
					else
					{
						this._grupoID = default(int);
					}
					this.SendPropertyChanged("grupo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.historico")]
	public partial class historico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _documentoid;
		
		private System.DateTime _data;
		
		private string _descricao;
		
		private System.Guid _usuarioid;
		
		private int _statusid;
		
		private int _pastaid;
		
		private int _estruturaid;
		
		private EntityRef<documento> _documento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndocumentoidChanging(int value);
    partial void OndocumentoidChanged();
    partial void OndataChanging(System.DateTime value);
    partial void OndataChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    partial void OnusuarioidChanging(System.Guid value);
    partial void OnusuarioidChanged();
    partial void OnstatusidChanging(int value);
    partial void OnstatusidChanged();
    partial void OnpastaidChanging(int value);
    partial void OnpastaidChanged();
    partial void OnestruturaidChanging(int value);
    partial void OnestruturaidChanged();
    #endregion
		
		public historico()
		{
			this._documento = default(EntityRef<documento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_documentoid", DbType="Int NOT NULL")]
		public int documentoid
		{
			get
			{
				return this._documentoid;
			}
			set
			{
				if ((this._documentoid != value))
				{
					if (this._documento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndocumentoidChanging(value);
					this.SendPropertyChanging();
					this._documentoid = value;
					this.SendPropertyChanged("documentoid");
					this.OndocumentoidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="DateTime NOT NULL")]
		public System.DateTime data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid usuarioid
		{
			get
			{
				return this._usuarioid;
			}
			set
			{
				if ((this._usuarioid != value))
				{
					this.OnusuarioidChanging(value);
					this.SendPropertyChanging();
					this._usuarioid = value;
					this.SendPropertyChanged("usuarioid");
					this.OnusuarioidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusid", DbType="Int NOT NULL")]
		public int statusid
		{
			get
			{
				return this._statusid;
			}
			set
			{
				if ((this._statusid != value))
				{
					this.OnstatusidChanging(value);
					this.SendPropertyChanging();
					this._statusid = value;
					this.SendPropertyChanged("statusid");
					this.OnstatusidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pastaid", DbType="Int NOT NULL")]
		public int pastaid
		{
			get
			{
				return this._pastaid;
			}
			set
			{
				if ((this._pastaid != value))
				{
					this.OnpastaidChanging(value);
					this.SendPropertyChanging();
					this._pastaid = value;
					this.SendPropertyChanged("pastaid");
					this.OnpastaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estruturaid", DbType="Int NOT NULL")]
		public int estruturaid
		{
			get
			{
				return this._estruturaid;
			}
			set
			{
				if ((this._estruturaid != value))
				{
					this.OnestruturaidChanging(value);
					this.SendPropertyChanging();
					this._estruturaid = value;
					this.SendPropertyChanged("estruturaid");
					this.OnestruturaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="documento_historico", Storage="_documento", ThisKey="documentoid", OtherKey="id", IsForeignKey=true)]
		public documento documento
		{
			get
			{
				return this._documento.Entity;
			}
			set
			{
				documento previousValue = this._documento.Entity;
				if (((previousValue != value) 
							|| (this._documento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._documento.Entity = null;
						previousValue.historicos.Remove(this);
					}
					this._documento.Entity = value;
					if ((value != null))
					{
						value.historicos.Add(this);
						this._documentoid = value.id;
					}
					else
					{
						this._documentoid = default(int);
					}
					this.SendPropertyChanged("documento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.notificacao")]
	public partial class notificacao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Guid _remetenteid;
		
		private System.Guid _destinatarioid;
		
		private bool _pendente;
		
		private System.DateTime _data;
		
		private int _processoid;
		
		private string _mensagem;
		
		private bool _realizado;
		
		private bool _visto;
		
		private string _observacoes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnremetenteidChanging(System.Guid value);
    partial void OnremetenteidChanged();
    partial void OndestinatarioidChanging(System.Guid value);
    partial void OndestinatarioidChanged();
    partial void OnpendenteChanging(bool value);
    partial void OnpendenteChanged();
    partial void OndataChanging(System.DateTime value);
    partial void OndataChanged();
    partial void OnprocessoidChanging(int value);
    partial void OnprocessoidChanged();
    partial void OnmensagemChanging(string value);
    partial void OnmensagemChanged();
    partial void OnrealizadoChanging(bool value);
    partial void OnrealizadoChanged();
    partial void OnvistoChanging(bool value);
    partial void OnvistoChanged();
    partial void OnobservacoesChanging(string value);
    partial void OnobservacoesChanged();
    #endregion
		
		public notificacao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remetenteid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid remetenteid
		{
			get
			{
				return this._remetenteid;
			}
			set
			{
				if ((this._remetenteid != value))
				{
					this.OnremetenteidChanging(value);
					this.SendPropertyChanging();
					this._remetenteid = value;
					this.SendPropertyChanged("remetenteid");
					this.OnremetenteidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destinatarioid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid destinatarioid
		{
			get
			{
				return this._destinatarioid;
			}
			set
			{
				if ((this._destinatarioid != value))
				{
					this.OndestinatarioidChanging(value);
					this.SendPropertyChanging();
					this._destinatarioid = value;
					this.SendPropertyChanged("destinatarioid");
					this.OndestinatarioidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pendente", DbType="Bit NOT NULL")]
		public bool pendente
		{
			get
			{
				return this._pendente;
			}
			set
			{
				if ((this._pendente != value))
				{
					this.OnpendenteChanging(value);
					this.SendPropertyChanging();
					this._pendente = value;
					this.SendPropertyChanged("pendente");
					this.OnpendenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="DateTime NOT NULL")]
		public System.DateTime data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_processoid", DbType="Int NOT NULL")]
		public int processoid
		{
			get
			{
				return this._processoid;
			}
			set
			{
				if ((this._processoid != value))
				{
					this.OnprocessoidChanging(value);
					this.SendPropertyChanging();
					this._processoid = value;
					this.SendPropertyChanged("processoid");
					this.OnprocessoidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mensagem", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string mensagem
		{
			get
			{
				return this._mensagem;
			}
			set
			{
				if ((this._mensagem != value))
				{
					this.OnmensagemChanging(value);
					this.SendPropertyChanging();
					this._mensagem = value;
					this.SendPropertyChanged("mensagem");
					this.OnmensagemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_realizado", DbType="Bit NOT NULL")]
		public bool realizado
		{
			get
			{
				return this._realizado;
			}
			set
			{
				if ((this._realizado != value))
				{
					this.OnrealizadoChanging(value);
					this.SendPropertyChanging();
					this._realizado = value;
					this.SendPropertyChanged("realizado");
					this.OnrealizadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visto", DbType="Bit NOT NULL")]
		public bool visto
		{
			get
			{
				return this._visto;
			}
			set
			{
				if ((this._visto != value))
				{
					this.OnvistoChanging(value);
					this.SendPropertyChanging();
					this._visto = value;
					this.SendPropertyChanged("visto");
					this.OnvistoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoes", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string observacoes
		{
			get
			{
				return this._observacoes;
			}
			set
			{
				if ((this._observacoes != value))
				{
					this.OnobservacoesChanging(value);
					this.SendPropertyChanging();
					this._observacoes = value;
					this.SendPropertyChanged("observacoes");
					this.OnobservacoesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ocorrencia")]
	public partial class Ocorrencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _documentoid;
		
		private int _palavraid;
		
		private int _ocorrencia1;
		
		private EntityRef<Dicionario> _Dicionario;
		
		private EntityRef<registro> _registro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndocumentoidChanging(int value);
    partial void OndocumentoidChanged();
    partial void OnpalavraidChanging(int value);
    partial void OnpalavraidChanged();
    partial void Onocorrencia1Changing(int value);
    partial void Onocorrencia1Changed();
    #endregion
		
		public Ocorrencia()
		{
			this._Dicionario = default(EntityRef<Dicionario>);
			this._registro = default(EntityRef<registro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_documentoid", DbType="Int NOT NULL")]
		public int documentoid
		{
			get
			{
				return this._documentoid;
			}
			set
			{
				if ((this._documentoid != value))
				{
					if (this._registro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndocumentoidChanging(value);
					this.SendPropertyChanging();
					this._documentoid = value;
					this.SendPropertyChanged("documentoid");
					this.OndocumentoidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavraid", DbType="Int NOT NULL")]
		public int palavraid
		{
			get
			{
				return this._palavraid;
			}
			set
			{
				if ((this._palavraid != value))
				{
					if (this._Dicionario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpalavraidChanging(value);
					this.SendPropertyChanging();
					this._palavraid = value;
					this.SendPropertyChanged("palavraid");
					this.OnpalavraidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ocorrencia", Storage="_ocorrencia1", DbType="Int NOT NULL")]
		public int ocorrencia1
		{
			get
			{
				return this._ocorrencia1;
			}
			set
			{
				if ((this._ocorrencia1 != value))
				{
					this.Onocorrencia1Changing(value);
					this.SendPropertyChanging();
					this._ocorrencia1 = value;
					this.SendPropertyChanged("ocorrencia1");
					this.Onocorrencia1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dicionario_Ocorrencia", Storage="_Dicionario", ThisKey="palavraid", OtherKey="id", IsForeignKey=true)]
		public Dicionario Dicionario
		{
			get
			{
				return this._Dicionario.Entity;
			}
			set
			{
				Dicionario previousValue = this._Dicionario.Entity;
				if (((previousValue != value) 
							|| (this._Dicionario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dicionario.Entity = null;
						previousValue.Ocorrencias.Remove(this);
					}
					this._Dicionario.Entity = value;
					if ((value != null))
					{
						value.Ocorrencias.Add(this);
						this._palavraid = value.id;
					}
					else
					{
						this._palavraid = default(int);
					}
					this.SendPropertyChanged("Dicionario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="registro_Ocorrencia", Storage="_registro", ThisKey="documentoid", OtherKey="id", IsForeignKey=true)]
		public registro registro
		{
			get
			{
				return this._registro.Entity;
			}
			set
			{
				registro previousValue = this._registro.Entity;
				if (((previousValue != value) 
							|| (this._registro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._registro.Entity = null;
						previousValue.Ocorrencias.Remove(this);
					}
					this._registro.Entity = value;
					if ((value != null))
					{
						value.Ocorrencias.Add(this);
						this._documentoid = value.id;
					}
					else
					{
						this._documentoid = default(int);
					}
					this.SendPropertyChanged("registro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pagina")]
	public partial class pagina : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _numero;
		
		private int _documentoid;
		
		private string _conteudo;
		
		private EntityRef<documento> _documento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnumeroChanging(int value);
    partial void OnnumeroChanged();
    partial void OndocumentoidChanging(int value);
    partial void OndocumentoidChanged();
    partial void OnconteudoChanging(string value);
    partial void OnconteudoChanged();
    #endregion
		
		public pagina()
		{
			this._documento = default(EntityRef<documento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="Int NOT NULL")]
		public int numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				if ((this._numero != value))
				{
					this.OnnumeroChanging(value);
					this.SendPropertyChanging();
					this._numero = value;
					this.SendPropertyChanged("numero");
					this.OnnumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_documentoid", DbType="Int NOT NULL")]
		public int documentoid
		{
			get
			{
				return this._documentoid;
			}
			set
			{
				if ((this._documentoid != value))
				{
					if (this._documento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndocumentoidChanging(value);
					this.SendPropertyChanging();
					this._documentoid = value;
					this.SendPropertyChanged("documentoid");
					this.OndocumentoidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conteudo", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string conteudo
		{
			get
			{
				return this._conteudo;
			}
			set
			{
				if ((this._conteudo != value))
				{
					this.OnconteudoChanging(value);
					this.SendPropertyChanging();
					this._conteudo = value;
					this.SendPropertyChanged("conteudo");
					this.OnconteudoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="documento_pagina", Storage="_documento", ThisKey="documentoid", OtherKey="id", IsForeignKey=true)]
		public documento documento
		{
			get
			{
				return this._documento.Entity;
			}
			set
			{
				documento previousValue = this._documento.Entity;
				if (((previousValue != value) 
							|| (this._documento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._documento.Entity = null;
						previousValue.paginas.Remove(this);
					}
					this._documento.Entity = value;
					if ((value != null))
					{
						value.paginas.Add(this);
						this._documentoid = value.id;
					}
					else
					{
						this._documentoid = default(int);
					}
					this.SendPropertyChanged("documento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pasta")]
	public partial class pasta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _pastasuperiorid;
		
		private string _nome;
		
		private System.Guid _usuarioid;
		
		private bool _privado;
		
		private string _observacoes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpastasuperioridChanging(int value);
    partial void OnpastasuperioridChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnusuarioidChanging(System.Guid value);
    partial void OnusuarioidChanged();
    partial void OnprivadoChanging(bool value);
    partial void OnprivadoChanged();
    partial void OnobservacoesChanging(string value);
    partial void OnobservacoesChanged();
    #endregion
		
		public pasta()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pastasuperiorid", DbType="Int NOT NULL")]
		public int pastasuperiorid
		{
			get
			{
				return this._pastasuperiorid;
			}
			set
			{
				if ((this._pastasuperiorid != value))
				{
					this.OnpastasuperioridChanging(value);
					this.SendPropertyChanging();
					this._pastasuperiorid = value;
					this.SendPropertyChanged("pastasuperiorid");
					this.OnpastasuperioridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid usuarioid
		{
			get
			{
				return this._usuarioid;
			}
			set
			{
				if ((this._usuarioid != value))
				{
					this.OnusuarioidChanging(value);
					this.SendPropertyChanging();
					this._usuarioid = value;
					this.SendPropertyChanged("usuarioid");
					this.OnusuarioidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_privado", DbType="Bit NOT NULL")]
		public bool privado
		{
			get
			{
				return this._privado;
			}
			set
			{
				if ((this._privado != value))
				{
					this.OnprivadoChanging(value);
					this.SendPropertyChanging();
					this._privado = value;
					this.SendPropertyChanged("privado");
					this.OnprivadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoes", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string observacoes
		{
			get
			{
				return this._observacoes;
			}
			set
			{
				if ((this._observacoes != value))
				{
					this.OnobservacoesChanging(value);
					this.SendPropertyChanging();
					this._observacoes = value;
					this.SendPropertyChanged("observacoes");
					this.OnobservacoesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.processo")]
	public partial class processo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nome;
		
		private string _descricao;
		
		private System.DateTime _data;
		
		private bool _ativo;
		
		private System.Guid _usuarioid;
		
		private int _estruturaid;
		
		private bool _arquivado;
		
		private string _chave;
		
		private string _observacoes;
		
		private EntitySet<evento> _eventos;
		
		private EntityRef<estrutura> _estrutura;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    partial void OndataChanging(System.DateTime value);
    partial void OndataChanged();
    partial void OnativoChanging(bool value);
    partial void OnativoChanged();
    partial void OnusuarioidChanging(System.Guid value);
    partial void OnusuarioidChanged();
    partial void OnestruturaidChanging(int value);
    partial void OnestruturaidChanged();
    partial void OnarquivadoChanging(bool value);
    partial void OnarquivadoChanged();
    partial void OnchaveChanging(string value);
    partial void OnchaveChanged();
    partial void OnobservacoesChanging(string value);
    partial void OnobservacoesChanged();
    #endregion
		
		public processo()
		{
			this._eventos = new EntitySet<evento>(new Action<evento>(this.attach_eventos), new Action<evento>(this.detach_eventos));
			this._estrutura = default(EntityRef<estrutura>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="DateTime NOT NULL")]
		public System.DateTime data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ativo", DbType="Bit NOT NULL")]
		public bool ativo
		{
			get
			{
				return this._ativo;
			}
			set
			{
				if ((this._ativo != value))
				{
					this.OnativoChanging(value);
					this.SendPropertyChanging();
					this._ativo = value;
					this.SendPropertyChanged("ativo");
					this.OnativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid usuarioid
		{
			get
			{
				return this._usuarioid;
			}
			set
			{
				if ((this._usuarioid != value))
				{
					this.OnusuarioidChanging(value);
					this.SendPropertyChanging();
					this._usuarioid = value;
					this.SendPropertyChanged("usuarioid");
					this.OnusuarioidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estruturaid", DbType="Int NOT NULL")]
		public int estruturaid
		{
			get
			{
				return this._estruturaid;
			}
			set
			{
				if ((this._estruturaid != value))
				{
					if (this._estrutura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnestruturaidChanging(value);
					this.SendPropertyChanging();
					this._estruturaid = value;
					this.SendPropertyChanged("estruturaid");
					this.OnestruturaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arquivado", DbType="Bit NOT NULL")]
		public bool arquivado
		{
			get
			{
				return this._arquivado;
			}
			set
			{
				if ((this._arquivado != value))
				{
					this.OnarquivadoChanging(value);
					this.SendPropertyChanging();
					this._arquivado = value;
					this.SendPropertyChanged("arquivado");
					this.OnarquivadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chave", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string chave
		{
			get
			{
				return this._chave;
			}
			set
			{
				if ((this._chave != value))
				{
					this.OnchaveChanging(value);
					this.SendPropertyChanging();
					this._chave = value;
					this.SendPropertyChanged("chave");
					this.OnchaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoes", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string observacoes
		{
			get
			{
				return this._observacoes;
			}
			set
			{
				if ((this._observacoes != value))
				{
					this.OnobservacoesChanging(value);
					this.SendPropertyChanging();
					this._observacoes = value;
					this.SendPropertyChanged("observacoes");
					this.OnobservacoesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="processo_evento", Storage="_eventos", ThisKey="id", OtherKey="processoid")]
		public EntitySet<evento> eventos
		{
			get
			{
				return this._eventos;
			}
			set
			{
				this._eventos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="estrutura_processo", Storage="_estrutura", ThisKey="estruturaid", OtherKey="id", IsForeignKey=true)]
		public estrutura estrutura
		{
			get
			{
				return this._estrutura.Entity;
			}
			set
			{
				estrutura previousValue = this._estrutura.Entity;
				if (((previousValue != value) 
							|| (this._estrutura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._estrutura.Entity = null;
						previousValue.processos.Remove(this);
					}
					this._estrutura.Entity = value;
					if ((value != null))
					{
						value.processos.Add(this);
						this._estruturaid = value.id;
					}
					else
					{
						this._estruturaid = default(int);
					}
					this.SendPropertyChanged("estrutura");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eventos(evento entity)
		{
			this.SendPropertyChanging();
			entity.processo = this;
		}
		
		private void detach_eventos(evento entity)
		{
			this.SendPropertyChanging();
			entity.processo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProcessoUsuario")]
	public partial class ProcessoUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Guid _usuarioID;
		
		private int _processoid;
		
		private bool _ativo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusuarioIDChanging(System.Guid value);
    partial void OnusuarioIDChanged();
    partial void OnprocessoidChanging(int value);
    partial void OnprocessoidChanged();
    partial void OnativoChanging(bool value);
    partial void OnativoChanged();
    #endregion
		
		public ProcessoUsuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid usuarioID
		{
			get
			{
				return this._usuarioID;
			}
			set
			{
				if ((this._usuarioID != value))
				{
					this.OnusuarioIDChanging(value);
					this.SendPropertyChanging();
					this._usuarioID = value;
					this.SendPropertyChanged("usuarioID");
					this.OnusuarioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_processoid", DbType="Int NOT NULL")]
		public int processoid
		{
			get
			{
				return this._processoid;
			}
			set
			{
				if ((this._processoid != value))
				{
					this.OnprocessoidChanging(value);
					this.SendPropertyChanging();
					this._processoid = value;
					this.SendPropertyChanged("processoid");
					this.OnprocessoidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ativo", DbType="Bit NOT NULL")]
		public bool ativo
		{
			get
			{
				return this._ativo;
			}
			set
			{
				if ((this._ativo != value))
				{
					this.OnativoChanging(value);
					this.SendPropertyChanging();
					this._ativo = value;
					this.SendPropertyChanged("ativo");
					this.OnativoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.registro")]
	public partial class registro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _arquivo;
		
		private int _qtdPagina;
		
		private string _hash;
		
		private bool _ativo;
		
		private string _chave;
		
		private string _link;
		
		private EntitySet<Ocorrencia> _Ocorrencias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnarquivoChanging(string value);
    partial void OnarquivoChanged();
    partial void OnqtdPaginaChanging(int value);
    partial void OnqtdPaginaChanged();
    partial void OnhashChanging(string value);
    partial void OnhashChanged();
    partial void OnativoChanging(bool value);
    partial void OnativoChanged();
    partial void OnchaveChanging(string value);
    partial void OnchaveChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    #endregion
		
		public registro()
		{
			this._Ocorrencias = new EntitySet<Ocorrencia>(new Action<Ocorrencia>(this.attach_Ocorrencias), new Action<Ocorrencia>(this.detach_Ocorrencias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arquivo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string arquivo
		{
			get
			{
				return this._arquivo;
			}
			set
			{
				if ((this._arquivo != value))
				{
					this.OnarquivoChanging(value);
					this.SendPropertyChanging();
					this._arquivo = value;
					this.SendPropertyChanged("arquivo");
					this.OnarquivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qtdPagina", DbType="Int NOT NULL")]
		public int qtdPagina
		{
			get
			{
				return this._qtdPagina;
			}
			set
			{
				if ((this._qtdPagina != value))
				{
					this.OnqtdPaginaChanging(value);
					this.SendPropertyChanging();
					this._qtdPagina = value;
					this.SendPropertyChanged("qtdPagina");
					this.OnqtdPaginaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hash", DbType="VarChar(255)")]
		public string hash
		{
			get
			{
				return this._hash;
			}
			set
			{
				if ((this._hash != value))
				{
					this.OnhashChanging(value);
					this.SendPropertyChanging();
					this._hash = value;
					this.SendPropertyChanged("hash");
					this.OnhashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ativo", DbType="Bit NOT NULL")]
		public bool ativo
		{
			get
			{
				return this._ativo;
			}
			set
			{
				if ((this._ativo != value))
				{
					this.OnativoChanging(value);
					this.SendPropertyChanging();
					this._ativo = value;
					this.SendPropertyChanged("ativo");
					this.OnativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chave", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string chave
		{
			get
			{
				return this._chave;
			}
			set
			{
				if ((this._chave != value))
				{
					this.OnchaveChanging(value);
					this.SendPropertyChanging();
					this._chave = value;
					this.SendPropertyChanged("chave");
					this.OnchaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="registro_Ocorrencia", Storage="_Ocorrencias", ThisKey="id", OtherKey="documentoid")]
		public EntitySet<Ocorrencia> Ocorrencias
		{
			get
			{
				return this._Ocorrencias;
			}
			set
			{
				this._Ocorrencias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ocorrencias(Ocorrencia entity)
		{
			this.SendPropertyChanging();
			entity.registro = this;
		}
		
		private void detach_Ocorrencias(Ocorrencia entity)
		{
			this.SendPropertyChanging();
			entity.registro = null;
		}
	}
}
#pragma warning restore 1591
